orchestrator:
  metrics:
    enabled: true
    bind: "0.0.0.0"
    port: 9315
  node_probe:
    enabled: true
    interval_s: 60
    timeout_s: 10
    prompt: "ping"
  gpu_monitor:
    enabled: true
    interval_s: 30  # Monitor every 30 seconds
    timeout_s: 15   # 15 second timeout for srun commands
    # Optional: override SLURM account/partition for monitoring
    # account: "monitoring-account"  
    # partition: "gpu-partition"
  notifications:
    type: log_only

deployments:
  - name: gpt-120b
    replicas: 2
    connectivity:
      mode: tunneled
      tunnel_mode: local
      orchestrator_host: "127.0.0.1"
      advertise_host: "127.0.0.1"
      local_port_range: [30001, 30099]
      ssh:
        user: "jonalsa"
        opts: ["-o", "ServerAliveInterval=15", "-o", "ExitOnForwardFailure=yes"]

    router:
      base_url: "http://127.0.0.1:30000"
      endpoints:
        list: "/list_workers"
        add: "/add_worker"
        remove: "/remove_worker"

    slurm:
      prefer: auto
      account: "chatgpt"
      reservation: "gpt"
      partition: "GPUQ"
      gres: "gpu:2"
      constraint: "h100"
      time_limit: "08:00:00"
      cpus_per_task: 24
      mem: "128G"
      log_dir: "/cluster/home/jonalsa/sg-logs"
      env:
        HF_HOME: "/cluster/home/jonalsa/.cache/huggingface"
        HUGGINGFACE_HUB_CACHE: "/cluster/home/jonalsa/.cache/huggingface"
        TORCH_CUDA_ARCH_LIST: "9.0"
        PYTORCH_NUM_THREADS: "{CPUS_PER_TASK}"
        MKL_NUM_THREADS: "{CPUS_PER_TASK}"
        OMP_NUM_THREADS: "{CPUS_PER_TASK}"
        RAYON_NUM_THREADS: "{CPUS_PER_TASK}"

    sglang:
      model_path: "openai/gpt-oss-120b"
      venv_path: "/cluster/home/jonalsa/sglang-test/.venv"
      args:
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "{PORT}"
        - "--reasoning-parser"
        - "gpt-oss"
        - "--grammar-backend"
        - "xgrammar"
        - "--tool-call-parser"
        - "gpt-oss"
        - "--context-length"
        - "96000"
        - "--mem-fraction-static"
        - "0.9"
        - "--tp"
        - "2"

    health:
      path: "/health"
      interval_s: 10
      timeout_s: 10
      consecutive_ok_for_ready: 2
      failures_to_unhealthy: 60

    policy:
      restart_backoff_s: 60
      deregister_grace_s: 10
      start_grace_period_s: 900
      predrain_seconds_before_walltime: 180
      node_blacklist_cooldown_s: 600
